import Providers from "@/components/Providers";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-300">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
